import { createMemoryEdge } from "./edges";
import { createMemoryNode } from "./nodes";
import { createProvenanceRef } from "./provenance";
import { GraphBundleSchema, type GraphBundle, type MemoryNode } from "./schemas";
export const MEMORY_GRAPH_FIXTURE_NOW = "2026-01-01T00:00:00.000Z";
export const fixtureProvenanceRefs = [
  createProvenanceRef({ source_id: "fixture:mission", source_type: "fixture", uri: "memory://fixture/mission", produced_by: "@stealtheye/memory-graph", produced_at: MEMORY_GRAPH_FIXTURE_NOW, summary: "Public-safe Memory Graph fixture mission." }),
  createProvenanceRef({ source_id: "repo-status:StealthEyeLLC/stealtheye-agent-os", source_type: "repo_status_packet", uri: "github://public/StealthEyeLLC/stealtheye-agent-os", produced_by: "@stealtheye/repo-status", produced_at: MEMORY_GRAPH_FIXTURE_NOW, summary: "Public repo status fixture." }),
  createProvenanceRef({ source_id: "build-12", source_type: "generated_build_state", uri: "docs://generated/build-012-manifest.json", produced_by: "scripts/stealtheye-build.mjs", produced_at: MEMORY_GRAPH_FIXTURE_NOW, summary: "Build 12 generated state fixture." })
];
export const fixtureNodes: MemoryNode[] = [
  createMemoryNode({ node_id: "memory:mission:build-12", node_type: "mission", title: "Build 12 Memory Graph", summary: "Implement fixture-only Memory Graph foundations.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["fixture:mission"], tags: ["build-12", "mission"], sensitivity: "internal_safe", public_private_boundary: "internal_reference", confidence: 0.98, retention_hint: "retain" }),
  createMemoryNode({ node_id: "memory:task:schemas", node_type: "task", title: "Define memory schemas", summary: "Create typed nodes, edges, provenance, and graph bundle schemas.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["fixture:mission"], tags: ["build-12", "schemas"], sensitivity: "internal_safe", public_private_boundary: "internal_reference", confidence: 0.96, retention_hint: "retain" }),
  createMemoryNode({ node_id: "memory:repo:StealthEyeLLC/stealtheye-agent-os", node_type: "repo", title: "StealthEyeLLC/stealtheye-agent-os", summary: "Public repository fixture for Memory Graph integration.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["repo-status:StealthEyeLLC/stealtheye-agent-os"], tags: ["repo", "public-github"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.95, retention_hint: "retain" }),
  createMemoryNode({ node_id: "memory:issue:1", node_type: "issue", title: "Master planning issue", summary: "Canonical public planning anchor for StealthEye Agent OS.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["repo-status:StealthEyeLLC/stealtheye-agent-os"], tags: ["issue", "planning"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.92, retention_hint: "retain" }),
  createMemoryNode({ node_id: "memory:fact:old", node_type: "fact", title: "Superseded target", summary: "Older fixture fact superseded by compacted summary.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["fixture:mission"], tags: ["fact", "stale"], sensitivity: "internal_safe", public_private_boundary: "internal_reference", confidence: 0.5, expires_at: "2025-01-01T00:00:00.000Z", retention_hint: "expire" }),
  createMemoryNode({ node_id: "memory:summary:repo-status", node_type: "summary", title: "Repo status summary", summary: "Repo status supports Build 12 context packet fixtures.", now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["repo-status:StealthEyeLLC/stealtheye-agent-os"], evidence_refs: ["evidence:repo-status"], receipt_refs: ["receipt:repo-status"], tags: ["summary", "repo-status"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.9, retention_hint: "retain" })
];
export const fixtureEdges = [
  createMemoryEdge({ edge_id: "memory:edge:task-belongs", from_node_id: "memory:task:schemas", to_node_id: "memory:mission:build-12", edge_type: "belongs_to", summary: "Schema task belongs to the Build 12 mission.", now: MEMORY_GRAPH_FIXTURE_NOW, confidence: 0.98 }),
  createMemoryEdge({ edge_id: "memory:edge:issue-supports", from_node_id: "memory:issue:1", to_node_id: "memory:mission:build-12", edge_type: "supports", summary: "Planning issue supports Build 12 context.", now: MEMORY_GRAPH_FIXTURE_NOW, confidence: 0.9 }),
  createMemoryEdge({ edge_id: "memory:edge:repo-observed", from_node_id: "memory:summary:repo-status", to_node_id: "memory:repo:StealthEyeLLC/stealtheye-agent-os", edge_type: "observed_in", summary: "Summary observed in public repo status fixture.", now: MEMORY_GRAPH_FIXTURE_NOW, confidence: 0.9 })
];
export const fixtureGraph: GraphBundle = GraphBundleSchema.parse({ graph_id: "memory-graph:fixture:build-12", schema_version: "stealtheye-memory-graph-bundle.v1", created_at: MEMORY_GRAPH_FIXTURE_NOW, updated_at: MEMORY_GRAPH_FIXTURE_NOW, nodes: fixtureNodes, edges: fixtureEdges, provenance_refs: fixtureProvenanceRefs, receipt_refs: ["receipt:repo-status"], integrity_digest: undefined, public_private_boundary: "internal_reference", sensitivity: "internal_safe", status: "draft" });
export const allNodeTypeFixtures: MemoryNode[] = ["agent", "tool", "branch", "pull_request", "workflow_run", "file", "receipt_event", "evidence_ref", "build", "decision", "capability", "policy", "gap"].map((node_type) => createMemoryNode({ node_id: `memory:${node_type}:fixture`, node_type: node_type as never, title: `${node_type} fixture`, summary: `Public-safe ${node_type} fixture.`, now: MEMORY_GRAPH_FIXTURE_NOW, source_refs: ["fixture:mission"], tags: ["fixture"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.9, retention_hint: "ephemeral_fixture" }));
