import { GraphBundleSchema, MemoryContextPacketSchema, type GraphBundle, type MemoryContextPacket, type MemoryEdge, type MemoryNode, type MemoryNodeType, type MemorySensitivity, type ProvenanceSourceType } from "./schemas";
export function validateMemoryGraph(graph: unknown): GraphBundle { return GraphBundleSchema.parse(graph); }
export function getNodeById(graph: GraphBundle, nodeId: string): MemoryNode | undefined { return graph.nodes.find((node) => node.node_id === nodeId); }
export function listNodesByType(graph: GraphBundle, nodeType: MemoryNodeType): MemoryNode[] { return graph.nodes.filter((node) => node.node_type === nodeType); }
export function listEdgesForNode(graph: GraphBundle, nodeId: string): MemoryEdge[] { return graph.edges.filter((edge) => edge.from_node_id === nodeId || edge.to_node_id === nodeId); }
export function findConnectedNodes(graph: GraphBundle, nodeId: string): MemoryNode[] { const ids = new Set(listEdgesForNode(graph, nodeId).flatMap((edge) => [edge.from_node_id, edge.to_node_id]).filter((id) => id !== nodeId)); return graph.nodes.filter((node) => ids.has(node.node_id)); }
export function searchNodesByTag(graph: GraphBundle, tag: string): MemoryNode[] { const needle = tag.toLowerCase(); return graph.nodes.filter((node) => node.tags.some((item) => item.toLowerCase() === needle)); }
export function searchNodesByText(graph: GraphBundle, text: string): MemoryNode[] { const needle = text.toLowerCase(); return graph.nodes.filter((node) => `${node.title} ${node.summary}`.toLowerCase().includes(needle)); }
export function filterBySourceType(graph: GraphBundle, sourceType: ProvenanceSourceType): MemoryNode[] { const sourceIds = new Set(graph.provenance_refs.filter((ref) => ref.source_type === sourceType).map((ref) => ref.source_id)); return graph.nodes.filter((node) => node.source_refs.some((ref) => sourceIds.has(ref))); }
export function filterByConfidence(graph: GraphBundle, minimum: number): MemoryNode[] { return graph.nodes.filter((node) => node.confidence >= minimum); }
export function filterBySensitivity(graph: GraphBundle, sensitivity: MemorySensitivity): MemoryNode[] { return graph.nodes.filter((node) => node.sensitivity === sensitivity); }
export function produceContextPacket(graph: GraphBundle, targetNodeId: string): MemoryContextPacket { const target = getNodeById(graph, targetNodeId); if (!target || !["mission", "task"].includes(target.node_type)) throw new Error("Context packets require a mission or task node."); const connected = findConnectedNodes(graph, targetNodeId); const nodes = [target, ...connected].filter((node, index, arr) => arr.findIndex((item) => item.node_id === node.node_id) === index); const nodeIds = new Set(nodes.map((node) => node.node_id)); const edges = graph.edges.filter((edge) => nodeIds.has(edge.from_node_id) && nodeIds.has(edge.to_node_id)); const sourceIds = new Set(nodes.flatMap((node) => node.source_refs)); const provenance_refs = graph.provenance_refs.filter((ref) => sourceIds.has(ref.source_id)); return MemoryContextPacketSchema.parse({ schema_version: "stealtheye-memory-context-packet.v1", graph_id: graph.graph_id, target_node_id: targetNodeId, nodes, edges, provenance_refs, public_safe_summary: `Context packet for ${target.title}: ${nodes.length} nodes and ${edges.length} edges.` }); }
export function producePublicSafeContextSummary(graph: GraphBundle): string { const allowed = graph.nodes.filter((node) => ["public", "internal_safe"].includes(node.sensitivity) && node.public_private_boundary !== "private_reference_placeholder"); return allowed.map((node) => `${node.node_type}:${node.title}`).join("; "); }
