import type { ReceiptEvent } from "@stealtheye/receipts-replay";
import type { RepoStatusPacket } from "@stealtheye/repo-status";
import { createMemoryEdge } from "./edges";
import { createMemoryNode } from "./nodes";
import { MemoryGraphReceiptPreviewSchema, type GraphBundle, type MemoryEdge, type MemoryGraphReceiptPreview, type MemoryNode } from "./schemas";
export function createMemoryNodeFromReceiptEvent(event: ReceiptEvent): MemoryNode { return createMemoryNode({ node_id: `memory:receipt_event:${event.event_id}`, node_type: "receipt_event", title: `Receipt event ${event.event_type}`, summary: event.summary, now: event.timestamp, source_refs: [event.event_id], evidence_refs: event.evidence_refs, receipt_refs: [event.event_id], tags: ["receipt", event.source_subsystem, event.event_type], sensitivity: event.sensitivity === "public" ? "public" : "internal_safe", public_private_boundary: event.public_private_boundary === "public_safe" ? "public_safe" : "internal_reference", confidence: 1, retention_hint: "retain", attributes: { mission_id: event.mission_id, actor_id: event.actor_id, subject_id: event.subject_id } }); }
export function createMemoryNodeFromRepoStatusPacket(packet: RepoStatusPacket): MemoryNode { return createMemoryNode({ node_id: `memory:repo:${packet.target.full_name}`, node_type: "repo", title: packet.target.full_name, summary: packet.summary, now: packet.generated_at, source_refs: [`repo-status:${packet.target.full_name}`], receipt_refs: packet.receipts.map((receipt) => receipt.receipt_event_id), tags: ["repo-status", "public-github"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.95, retention_hint: "retain", attributes: { default_branch: packet.repository.default_branch } }); }
export function createRepoStatusNodes(packet: RepoStatusPacket): MemoryNode[] { const now = packet.generated_at; const repo = createMemoryNodeFromRepoStatusPacket(packet); const prs = packet.pull_requests.map((pr) => createMemoryNode({ node_id: `memory:pull_request:${packet.target.full_name}:${pr.number}`, node_type: "pull_request", title: `PR #${pr.number}: ${pr.title}`, summary: `${pr.state} PR targeting ${pr.base_ref}.`, now, source_refs: [`repo-status:${packet.target.full_name}`], tags: ["repo-status", "pull-request"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.95, retention_hint: "retain" })); const issues = packet.issues.map((issue) => createMemoryNode({ node_id: `memory:issue:${packet.target.full_name}:${issue.number}`, node_type: "issue", title: `Issue #${issue.number}: ${issue.title}`, summary: `${issue.state} public issue.`, now, source_refs: [`repo-status:${packet.target.full_name}`], tags: ["repo-status", "issue"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.95, retention_hint: "retain" })); const checks = packet.workflow_checks.map((check) => createMemoryNode({ node_id: `memory:workflow_run:${packet.target.full_name}:${check.run_id ?? check.name}`, node_type: "workflow_run", title: check.name, summary: `${check.status}/${check.conclusion ?? "unknown"} for ${check.ref}.`, now, source_refs: [`repo-status:${packet.target.full_name}`], tags: ["repo-status", "workflow"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.9, retention_hint: "retain" })); const files = packet.files.map((file) => createMemoryNode({ node_id: `memory:file:${packet.target.full_name}:${file.path}`, node_type: "file", title: file.path, summary: `Public-safe file metadata for ${file.path}.`, now, source_refs: [`repo-status:${packet.target.full_name}`], tags: ["repo-status", "file"], sensitivity: "public", public_private_boundary: "public_safe", confidence: 0.9, retention_hint: "retain" })); return [repo, ...prs, ...issues, ...checks, ...files]; }
export function createRepoStatusEdges(packet: RepoStatusPacket): MemoryEdge[] { const repoId = `memory:repo:${packet.target.full_name}`; const now = packet.generated_at; return createRepoStatusNodes(packet).filter((node) => node.node_id !== repoId).map((node, index) => createMemoryEdge({ edge_id: `memory:edge:repo-status:${index}`, from_node_id: node.node_id, to_node_id: repoId, edge_type: node.node_type === "workflow_run" ? "observed_in" : "belongs_to", summary: `${node.title} belongs to or was observed in ${packet.target.full_name}.`, now, confidence: 0.9 })); }
export function createMemoryNodeFromGeneratedBuildStateRef(input: { build: number; title: string; uri: string; produced_at: string }): MemoryNode { return createMemoryNode({ node_id: `memory:build:${input.build}`, node_type: "build", title: `Build ${input.build}: ${input.title}`, summary: `Generated build-state reference ${input.uri}.`, now: input.produced_at, source_refs: [`build-${input.build}`], tags: ["build-automation", `build-${input.build}`], sensitivity: "public", public_private_boundary: "public_safe", confidence: 1, retention_hint: "retain", attributes: { uri: input.uri } }); }
export function createMemoryGraphReceiptPreview(graph: GraphBundle, now = graph.updated_at): MemoryGraphReceiptPreview { return MemoryGraphReceiptPreviewSchema.parse({ schema_version: "stealtheye-memory-graph-receipt-preview.v1", preview_id: `memory-graph-preview:${graph.graph_id}`, graph_id: graph.graph_id, generated_at: now, node_count: graph.nodes.length, edge_count: graph.edges.length, receipt_refs: graph.receipt_refs, public_safe: true, no_durable_storage: true, no_embeddings: true, summary: `Previewed memory graph ${graph.graph_id} without durable storage, embeddings, or live writes.` }); }
export function linkMemoryGraphEventsToReceiptRefs(nodes: MemoryNode[], receiptRefs: string[]): MemoryNode[] { const refs = [...new Set(receiptRefs)].sort(); return nodes.map((node) => ({ ...node, receipt_refs: [...new Set([...node.receipt_refs, ...refs])].sort() })); }
