import { describe, expect, it } from "vitest";
import { AppHostToolNameSchema } from "@stealtheye/app-host";
import { MCP_RUNTIME_SAFE_TOOL_NAMES, RUNTIME_RESOURCE_URIS, assertRuntimeToolInventorySafe, createDevModeConnectionInfo, createLocalDevTransport, createMcpRuntimeServer, getRuntimeCapabilities, getRuntimeHealth, listRuntimeResources, listRuntimeTools, readRuntimeResource } from "../src";
const repoToolNames = ["repo.status.summary", "repo.metadata.read", "repo.branch.read", "repo.pr.list", "repo.pr.read", "repo.issue.list", "repo.issue.read", "repo.workflow.status.read", "repo.file.metadata.read", "repo.file.content.read"] as const;
const memoryToolNames = ["memory.graph.preview", "memory.node.search.preview", "memory.context.preview", "memory.retention.preview"] as const;
const mutationForbiddenName = /delete|commit|create|update|write|rerun|dispatch|deploy|payment|purchase|browser\.click|browser\.type|production_url|embedding|vector/i;
const mutationForbiddenEffect = /purchase|payment|deploy|commit_branch|write_branch_files|open_pr|update_pr|update_issue|rerun_ci|dispatch_workflow|mutate_repo_settings|read_secrets|read_private_repo|browser_click|credentialed|embedding|vector|storage_write/i;
const secretLike = new RegExp(["AKIA[0-9A-Z]{16}", "BEGIN (RSA|OPENSSH|EC|DSA) PRIVATE KEY", "client_secret", "PRIVATE_KEY", "customer_ssn", "credit card"].join("|"), "i");
function receiptOf(result: { receipt?: unknown }) { expect(result.receipt).toBeTruthy(); return result.receipt as { public_safe?: boolean; no_live_side_effects?: boolean; no_durable_storage?: boolean; no_embeddings?: boolean; target_repo?: string }; }
describe("MCP Runtime local/dev, repo read-only, and memory preview surface", () => {
  it("runtime health returns Build 12 safe status", () => { const health = getRuntimeHealth(); expect(health.status).toBe("ok"); expect(health.build).toBe(12); expect(health.local_dev_only).toBe(true); expect(health.production_ready).toBe(false); expect(health.live_write_capabilities).toBe(false); });
  it("runtime capabilities list safe tool families", () => { const capabilities = getRuntimeCapabilities(); expect(capabilities.tool_families).toEqual(["guard", "host", "memory", "mission", "policy", "registry", "repo"]); expect(capabilities.read_only_tools).toBe(true); expect(capabilities.live_write_tools).toBe(false); expect(capabilities.repo_status_read_only_tools).toEqual([...repoToolNames]); expect(capabilities.memory_graph_preview_tools).toEqual([...memoryToolNames]); });
  it("tool listing includes expected App Host, repo/status, and memory tools", () => { const names = listRuntimeTools().map((tool) => tool.name); for (const name of MCP_RUNTIME_SAFE_TOOL_NAMES) expect(names).toContain(name); for (const name of repoToolNames) expect(names).toContain(name); for (const name of memoryToolNames) expect(names).toContain(name); });
  it("tool descriptors are read-only and never live-write/destructive", () => { expect(assertRuntimeToolInventorySafe(listRuntimeTools())).toBe(true); for (const tool of listRuntimeTools()) { expect(tool.annotations.readOnlyHint).toBe(true); expect(tool.safety.readOnly).toBe(true); expect(tool.safety.liveWrite).toBe(false); expect(tool.safety.externalSideEffect).toBe(false); expect(tool.safety.destructive).toBe(false); if (tool.repo_status_tool) expect(tool.safety.liveCapabilityStatus).toBe("read_only_live"); else if (tool.memory_graph_tool) { expect(tool.safety.liveCapabilityStatus).toBe("fixture_only"); expect(tool.safety.previewOnly).toBe(true); expect(tool.safety.fixtureOnly).toBe(true); } else expect(tool.safety.liveCapabilityStatus).toBe("disabled"); } });
  it("no live write/destructive/storage/embedding tools are exposed", () => { for (const tool of listRuntimeTools()) { expect(tool.name).not.toMatch(mutationForbiddenName); expect(tool.safety.allowedEffects.join(" ")).not.toMatch(mutationForbiddenEffect); expect(tool.safety.liveWrite).toBe(false); expect(tool.safety.destructive).toBe(false); } });
  it("host and repo calls still succeed", async () => { expect((await createMcpRuntimeServer().callTool("host.health")).ok).toBe(true); const repo = await createMcpRuntimeServer().callTool("repo.status.summary"); expect(repo.ok).toBe(true); expect(receiptOf(repo).target_repo).toBe("StealthEyeLLC/stealtheye-agent-os"); });
  it("memory.graph.preview succeeds", async () => { const result = await createMcpRuntimeServer().callTool("memory.graph.preview"); expect(result.ok).toBe(true); expect((result.structuredContent as { graph: { graph_id: string } }).graph.graph_id).toContain("build-12"); expect(receiptOf(result).no_durable_storage).toBe(true); });
  it("memory.node.search.preview succeeds", async () => { const result = await createMcpRuntimeServer().callTool("memory.node.search.preview", { tag: "repo" }); expect(result.ok).toBe(true); expect((result.structuredContent as { nodes: unknown[] }).nodes.length).toBeGreaterThan(0); });
  it("memory.context.preview succeeds", async () => { const result = await createMcpRuntimeServer().callTool("memory.context.preview"); expect(result.ok).toBe(true); expect((result.structuredContent as { context: { target_node_id: string } }).context.target_node_id).toBe("memory:mission:build-12"); });
  it("memory.retention.preview succeeds", async () => { const result = await createMcpRuntimeServer().callTool("memory.retention.preview"); expect(result.ok).toBe(true); expect((result.structuredContent as { retention: { public_safe_summary: string } }).retention.public_safe_summary).toContain("deletes nothing"); });
  it("unsafe runtime names are rejected", async () => { await expect(createMcpRuntimeServer().callTool("memory.embedding.create")).rejects.toThrow(/Unknown runtime tool/); await expect(createMcpRuntimeServer().callTool("repo.commit.live")).rejects.toThrow(/Unknown runtime tool/); });
  it("resource and transport surfaces remain public-safe", async () => { expect(listRuntimeResources().map((r) => r.uri)).toContain(RUNTIME_RESOURCE_URIS.runtime); expect(readRuntimeResource(RUNTIME_RESOURCE_URIS.runtime).public_safe).toBe(true); expect(createDevModeConnectionInfo().public_safe).toBe(true); const transport = createLocalDevTransport(); expect((await transport.handle({ method: "POST", path: "/tools/call", body: { name: "memory.graph.preview" } })).status).toBe(200); });
  it("no real secret-like material, customer data, or live write endpoints appear in fixtures/descriptors", () => { const serialized = JSON.stringify({ tools: listRuntimeTools(), resources: listRuntimeResources(), devMode: createDevModeConnectionInfo() }); expect(serialized).not.toMatch(secretLike); for (const name of MCP_RUNTIME_SAFE_TOOL_NAMES) expect(AppHostToolNameSchema.safeParse(name).success).toBe(true); });
});
