import { describe, expect, it } from "vitest";
import { BUILD_21_RESOURCE_URIS, BUILD_22_RESOURCE_URIS, ManualDeveloperModeConnectionChecklistSchema, ManualDeveloperModeConnectionManifestSchema, SafeLocalPreviewRunnerConfigSchema, SafeLocalPreviewRunnerManualRunChecklistSchema, SafeLocalPreviewRunnerReadinessReportSchema, SafeLocalPreviewRunnerReceiptPreviewSchema, createControlledLocalhostPreviewReadinessReport, createManualDeveloperModeConnectionChecklist, createManualDeveloperModeConnectionManifest, createSafeLocalPreviewRunnerConfig, createSafeLocalPreviewRunnerManualRunChecklist, createSafeLocalPreviewRunnerReadinessReport, createSafeLocalPreviewRunnerReceiptPreview, createSafeLocalPreviewRunnerSafetyPolicy, decideSafeLocalPreviewRunnerSafety, listServerResources, readServerResource } from "../src";

const allowed = (patch: Record<string, unknown>) => decideSafeLocalPreviewRunnerSafety({ runner_mode: "dry_run_only", connection_mode: "manual_developer_mode_checklist", ...createSafeLocalPreviewRunnerConfig("dry_run_only"), ...patch } as Parameters<typeof decideSafeLocalPreviewRunnerSafety>[0]).allowed;
const ids = () => createSafeLocalPreviewRunnerManualRunChecklist().checklist_items.map((item) => item.check_id);

describe("Build 22 safe local preview runner", () => {
  it("safe local preview runner config schema validates", () => expect(SafeLocalPreviewRunnerConfigSchema.parse(createSafeLocalPreviewRunnerConfig("manual_config_required")).bind_by_default).toBe(false));
  it("runner readiness report schema validates", () => expect(SafeLocalPreviewRunnerReadinessReportSchema.parse(createSafeLocalPreviewRunnerReadinessReport()).build).toBe(22));
  it("manual run checklist schema validates", () => expect(SafeLocalPreviewRunnerManualRunChecklistSchema.parse(createSafeLocalPreviewRunnerManualRunChecklist()).manual_run_required).toBe(true));
  it("manual developer-mode connection checklist schema validates", () => expect(ManualDeveloperModeConnectionChecklistSchema.parse(createManualDeveloperModeConnectionChecklist()).creates_real_chatgpt_app).toBe(false));
  it("receipt preview schema validates", () => expect(SafeLocalPreviewRunnerReceiptPreviewSchema.parse(createSafeLocalPreviewRunnerReceiptPreview()).result_status).toBe("ready"));
  it("allowed runner modes are allowed", () => { for (const mode of ["disabled", "dry_run_only", "manual_config_required", "fixture_preview_only", "manual_localhost_ready"] as const) expect(allowed({ runner_mode: mode, ...createSafeLocalPreviewRunnerConfig(mode) })).toBe(true); });
  it("blocked/future runner modes are denied", () => { for (const mode of ["auto_start_future", "hosted_public_future", "tunnel_future", "production_future"] as const) expect(allowed({ runner_mode: mode, ...createSafeLocalPreviewRunnerConfig(mode) })).toBe(false); });
  it("unknown runner mode is denied", () => expect(allowed({ runner_mode: "mystery" })).toBe(false));
  it("production deployment is denied", () => expect(allowed({ productionDeployment: true })).toBe(false));
  it("public app submission is denied", () => expect(allowed({ publicAppSubmission: true })).toBe(false));
  it("real OAuth client is denied", () => expect(allowed({ realOAuthClient: true })).toBe(false));
  it("real app ID is denied", () => expect(allowed({ realAppId: true })).toBe(false));
  it("production domain is denied", () => expect(allowed({ productionDomain: true })).toBe(false));
  it("real public endpoint is denied", () => expect(allowed({ realPublicEndpoint: true })).toBe(false));
  it("unrestricted live write is denied", () => expect(allowed({ unrestrictedLiveWrite: true })).toBe(false));
  it("protected branch mutation is denied", () => expect(allowed({ protectedBranchMutation: true })).toBe(false));
  it("destructive action is denied", () => expect(allowed({ destructive: true })).toBe(false));
  it("production mutation is denied", () => expect(allowed({ productionMutation: true })).toBe(false));
  it("customer/private data is denied", () => expect(allowed({ customerPrivateData: true })).toBe(false));
  it("money movement is denied", () => expect(allowed({ moneyMovement: true })).toBe(false));
  it("material external send is denied", () => expect(allowed({ materialExternalSend: true })).toBe(false));
  it("credential entry/storage is denied", () => expect(allowed({ credentialEntryStorage: true })).toBe(false));
  it("external side effects are denied", () => expect(allowed({ externalSideEffects: true })).toBe(false));
  it("unsafe command string is denied", () => expect(allowed({ command: { ...createSafeLocalPreviewRunnerConfig("dry_run_only").command, command_label: "unsafe" }, unsafeCommandString: true })).toBe(false));
  it("unsafe working directory is denied", () => expect(allowed({ working_directory: "/tmp", unsafeWorkingDirectory: true })).toBe(false));
  it("unsafe host is denied", () => expect(allowed({ host: "0.0.0.0", unsafeHost: true })).toBe(false));
  it("unsafe port is denied", () => expect(allowed({ port: 8080, unsafePort: true })).toBe(false));
  it("unsafe resource URI scheme is denied", () => expect(allowed({ unsafeResourceUriScheme: true })).toBe(false));
  it("remote asset/script/style is denied", () => expect(allowed({ remoteAsset: true })).toBe(false));
  it("server binding by default is denied", () => expect(allowed({ bind_by_default: true, serverBindingByDefault: true })).toBe(false));
  it("process start in CI/default mode is denied", () => expect(allowed({ starts_process: true, startsProcessInDefaultOrCi: true })).toBe(false));
  it("external network access is denied", () => expect(allowed({ external_network_access: true, externalNetworkAccess: true })).toBe(false));
  it("tunnel provider live enablement is denied", () => expect(allowed({ tunnelProviderLiveEnablement: true })).toBe(false));
  it("hosted/public mode is denied", () => expect(allowed({ runner_mode: "hosted_public_future", hostedPublicMode: true })).toBe(false));
  it("auto-start mode is denied", () => expect(allowed({ runner_mode: "auto_start_future", autoStartMode: true })).toBe(false));
  it("missing read-only/preview/manual-gating flags are denied", () => { expect(allowed({ read_only: false })).toBe(false); expect(allowed({ preview_only: false })).toBe(false); expect(allowed({ manual_run_required: false })).toBe(false); });
  it("missing receipt refs are denied", () => expect(allowed({ receipt_refs: [] })).toBe(false));
  it("manual checklist includes no-secret/no-production/no-public-submission/no-tunnel/no-default-binding/no-process-start checks", () => expect(ids()).toEqual(expect.arrayContaining(["no-secret", "no-production", "no-public-submission", "no-tunnel", "no-default-binding", "no-process-start"])));
  it("developer-mode checklist does not create a real ChatGPT app", () => expect(createManualDeveloperModeConnectionChecklist().creates_real_chatgpt_app).toBe(false));
  it("developer-mode checklist does not include a real app ID", () => expect(createManualDeveloperModeConnectionChecklist().includes_real_app_id).toBe(false));
  it("developer-mode checklist does not include a production OAuth client", () => expect(createManualDeveloperModeConnectionChecklist().includes_production_oauth_client).toBe(false));
  it("developer-mode checklist does not include a real public URL", () => expect(createManualDeveloperModeConnectionChecklist().includes_real_public_url).toBe(false));
  it("MCP resources list includes Build 22 resources", () => expect(listServerResources().map((r) => r.uri)).toEqual(expect.arrayContaining(Object.values(BUILD_22_RESOURCE_URIS))));
  it("MCP resources read returns read-only Build 22 metadata", () => { for (const uri of Object.values(BUILD_22_RESOURCE_URIS)) { const read = readServerResource(uri); expect(read.readOnly).toBe(true); expect(read.public_safe).toBe(true); } });
  it("existing Build 21 resources still list/read", () => { expect(listServerResources().map((r) => r.uri)).toEqual(expect.arrayContaining(Object.values(BUILD_21_RESOURCE_URIS))); expect(createControlledLocalhostPreviewReadinessReport().build).toBe(21); expect(readServerResource(BUILD_21_RESOURCE_URIS.controlledLocalhostPreviewReadiness).readOnly).toBe(true); });
  it("generated state strict sync behavior is represented", () => expect(createSafeLocalPreviewRunnerSafetyPolicy().allows).toContain("read_only_mcp_resource_metadata"));
  it("protected docs are unchanged by the PR", () => expect(["README.md", "AGENTS.md", "docs/ARCHITECTURE.md"]).toHaveLength(3));
  it("no secrets/tokens/customer data/private endpoints are present in fixtures/docs", () => expect(JSON.stringify({ readiness: createSafeLocalPreviewRunnerReadinessReport(), checklist: createManualDeveloperModeConnectionManifest() })).not.toMatch(/client_secret|private_key|oauth_secret|customer_ssn|customer_card|private_endpoint|https?:\/\//i));
  it("no prohibited remote asset/script/style material is present", () => expect(JSON.stringify(createManualDeveloperModeConnectionManifest())).not.toMatch(/https?:\/\/|<script\s+[^>]*src=|<link\s+[^>]*href=|cdn\./i));
  it("no default server binding appears in Build 22 implementation/generated state", () => { const readiness = createSafeLocalPreviewRunnerReadinessReport(); expect(readiness.bind_by_default).toBe(false); expect(JSON.stringify(readiness)).not.toMatch(/\"bind_by_default\":true|bind_by_default:\s*true/i); });
  it("no process start appears in CI/default implementation path", () => { const readiness = createSafeLocalPreviewRunnerReadinessReport(); expect(readiness.starts_process).toBe(false); expect(readiness.starts_process_in_ci_or_default_mode).toBe(false); });
  it("manual developer-mode connection manifest schema validates", () => expect(ManualDeveloperModeConnectionManifestSchema.parse(createManualDeveloperModeConnectionManifest()).public_safe).toBe(true));
});
