import { BranchWritePlanSchema, createBranchWriteReceiptPreview, createFixtureBranchWriter, evaluateBranchWritePolicy, fixtureWriterCapabilities, guardDecisionsForBranchWritePlan, safeBranchWritePlan, trustedBranchWriteCapabilityToken, trustedBranchWriteRegistrySummary, type BranchWritePlan } from "@stealtheye/codeops";
import { McpRuntimeSchemaVersion, RuntimeToolDescriptorSchema, type RuntimeToolDescriptor } from "./schemas";
export type CodeOpsWriteRuntimeToolName="codeops.write.plan.preview"|"codeops.branch.write.preview"|"codeops.branch.write.fixture"|"codeops.write.receipt.preview";
const names: CodeOpsWriteRuntimeToolName[]=["codeops.write.plan.preview","codeops.branch.write.preview","codeops.branch.write.fixture","codeops.write.receipt.preview"];
const inputSchema={type:"object",additionalProperties:true}; const outputSchema={type:"object",additionalProperties:true};
function desc(name:CodeOpsWriteRuntimeToolName, description:string, readOnly:boolean, previewOnly:boolean, fixtureOnly:boolean): RuntimeToolDescriptor { return RuntimeToolDescriptorSchema.parse({ schema_version:McpRuntimeSchemaVersion.RuntimeToolDescriptor, name, description, inputSchema, outputSchema, annotations:{readOnlyHint:readOnly,destructiveHint:false,openWorldHint:false,idempotentHint:true}, riskTier:fixtureOnly&&!previewOnly?"medium":"low", safety:{ readOnly, previewOnly, fixtureOnly, destructive:false, live:false, liveWrite:false, externalSideEffect:false, liveCapabilityStatus: fixtureOnly?"fixture_only":"config_required", allowedEffects:["branch_safe_repo_write_modeling","policy_preview","guard_preview","receipt_preview",...(fixtureOnly?["fixture_branch_write_execution"]:[])], hardStopCategories:["protected_branch_mutation","raw_secrets_credentials","production_deploy_or_data_mutation","force_push_history_rewrite","weaken_ci_tests_security","deletion_destruction"], receiptExpectations:["policy_decision","guard_decision","target_repo_branch","file_list_summary","verification_commands","no_protected_branch_statement","no_sensitive_data_statement","fixture_or_preview_status","final_result"], evidenceExpectations:["public_safe_plan_summary","verification_commands","receipt_preview"] }, mcp_compatible:true, app_host_tool:false, repo_status_tool:false, memory_graph_tool:false, codeops_write_tool:true }); }
export function listCodeOpsWriteRuntimeTools(): RuntimeToolDescriptor[] { return [ desc("codeops.write.plan.preview","Preview a guarded CodeOps branch-write plan without executing a write.",true,true,false), desc("codeops.branch.write.preview","Run branch-write policy, Guard, and receipt preview in dry-run mode.",true,true,false), desc("codeops.branch.write.fixture","Execute the fixture-only branch-write writer; no external side effects occur.",false,false,true), desc("codeops.write.receipt.preview","Preview branch-write receipt events for policy, Guard, branch target, files, verification, and final status.",true,true,false) ]; }
export function isCodeOpsWriteRuntimeToolName(name:string): name is CodeOpsWriteRuntimeToolName { return names.includes(name as CodeOpsWriteRuntimeToolName); }
function planFrom(input:unknown): BranchWritePlan { const parsed=input&&typeof input==="object"&&!Array.isArray(input)?input as {plan?:unknown}:{}; return parsed.plan?BranchWritePlanSchema.parse(parsed.plan):safeBranchWritePlan; }
export function callCodeOpsWriteRuntimeTool(name:CodeOpsWriteRuntimeToolName, input:unknown={}) { const plan=planFrom(input); const writer=createFixtureBranchWriter(); if(name==="codeops.write.plan.preview"){ const guard_decisions=guardDecisionsForBranchWritePlan({plan,capability_tokens:[trustedBranchWriteCapabilityToken],registry_trust_summary:trustedBranchWriteRegistrySummary}); const policy_decision=evaluateBranchWritePolicy(plan, undefined, guard_decisions.map(d=>d.decision_id), guard_decisions.some(d=>d.decision==="deny"||d.decision==="escalate")); return {plan,policy_decision,guard_decisions,writer_capabilities:fixtureWriterCapabilities,previewOnly:true,live_write:false,external_side_effect:false}; } if(name==="codeops.branch.write.preview") return writer.previewWrite(plan); if(name==="codeops.branch.write.fixture") return writer.executeFixtureWrite(plan); if(name==="codeops.write.receipt.preview"){ const decision=writer.validatePlan(plan); return createBranchWriteReceiptPreview({plan,policy_decision:decision,guard_decision_refs:decision.guard_decision_refs,final_status:decision.allowed?"previewed":"denied"}); } throw new Error(`Unknown CodeOps write runtime tool: ${name}`); }
