import { createMemoryGraphReceiptPreview, fixtureGraph, produceContextPacket, producePublicSafeContextSummary, produceRetentionReport, searchNodesByTag, searchNodesByText } from "@stealtheye/memory-graph";
import { McpRuntimeSchemaVersion, RuntimeToolDescriptorSchema, type RuntimeToolDescriptor } from "./schemas";
export type MemoryGraphRuntimeToolName = "memory.graph.preview" | "memory.node.search.preview" | "memory.context.preview" | "memory.retention.preview";
const names: MemoryGraphRuntimeToolName[] = ["memory.graph.preview", "memory.node.search.preview", "memory.context.preview", "memory.retention.preview"];
const inputSchema = { type: "object", additionalProperties: true };
const outputSchema = { type: "object", additionalProperties: true };
const descriptions: Record<MemoryGraphRuntimeToolName, string> = {
  "memory.graph.preview": "Preview the Build 12 fixture-only in-memory graph bundle.",
  "memory.node.search.preview": "Search Build 12 fixture memory nodes by tag or title/summary substring.",
  "memory.context.preview": "Produce a fixture-only context packet for a mission or task node.",
  "memory.retention.preview": "Produce a fixture-only retention report without deleting or redacting anything."
};
export function listMemoryGraphRuntimeTools(): RuntimeToolDescriptor[] { return names.map((name) => RuntimeToolDescriptorSchema.parse({ schema_version: McpRuntimeSchemaVersion.RuntimeToolDescriptor, name, description: descriptions[name], inputSchema, outputSchema, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true }, riskTier: "low", safety: { readOnly: true, previewOnly: true, fixtureOnly: true, destructive: false, live: false, liveWrite: false, externalSideEffect: false, liveCapabilityStatus: "fixture_only", allowedEffects: ["fixture_memory_graph_preview"], hardStopCategories: ["raw_secrets_credentials", "money_billing_subscriptions", "production_deploy_or_data_mutation", "protected_branch_mutation", "force_push_history_rewrite", "weaken_ci_tests_security", "customer_data", "private_memory_ingestion"], receiptExpectations: ["memory_graph_receipt_preview", "fixture_only_no_storage", "no_embeddings"], evidenceExpectations: ["public_safe_fixture_summary"] }, mcp_compatible: true, app_host_tool: false, repo_status_tool: false, memory_graph_tool: true })); }
export function isMemoryGraphRuntimeToolName(name: string): name is MemoryGraphRuntimeToolName { return names.includes(name as MemoryGraphRuntimeToolName); }
function parse(input: unknown): { tag?: string; text?: string; nodeId?: string } { return input && typeof input === "object" && !Array.isArray(input) ? input as { tag?: string; text?: string; nodeId?: string } : {}; }
export function callMemoryGraphRuntimeTool(name: MemoryGraphRuntimeToolName, input: unknown = {}) { const parsed = parse(input); if (name === "memory.graph.preview") return { graph: fixtureGraph, receipt: createMemoryGraphReceiptPreview(fixtureGraph), public_safe_summary: producePublicSafeContextSummary(fixtureGraph) }; if (name === "memory.node.search.preview") return { nodes: parsed.tag ? searchNodesByTag(fixtureGraph, parsed.tag) : searchNodesByText(fixtureGraph, parsed.text ?? "Build 12"), receipt: createMemoryGraphReceiptPreview(fixtureGraph) }; if (name === "memory.context.preview") return { context: produceContextPacket(fixtureGraph, parsed.nodeId ?? "memory:mission:build-12"), receipt: createMemoryGraphReceiptPreview(fixtureGraph) }; if (name === "memory.retention.preview") return { retention: produceRetentionReport(fixtureGraph), receipt: createMemoryGraphReceiptPreview(fixtureGraph) }; throw new Error(`Unknown memory graph runtime tool: ${name}`); }
