import { createMemoryGraphReceiptPreview, filterNodesBySensitivity, memoryGraphFixture, produceContextPacket, producePublicSafeContextSummary, producePublicSafeRetentionSummary, produceRetentionReport, searchNodesByTag, searchNodesByText } from "@stealtheye/memory-graph";
import { McpRuntimeSchemaVersion, RuntimeToolDescriptorSchema, type RuntimeToolDescriptor } from "./schemas";
export type MemoryGraphRuntimeToolName = "memory.graph.preview" | "memory.node.search.preview" | "memory.context.preview" | "memory.retention.preview";
const memoryToolNames: MemoryGraphRuntimeToolName[] = ["memory.graph.preview","memory.node.search.preview","memory.context.preview","memory.retention.preview"];
const inputSchema = { type: "object", additionalProperties: true };
const outputSchema = { type: "object", additionalProperties: true };
function descriptor(name: MemoryGraphRuntimeToolName, description: string): RuntimeToolDescriptor { return RuntimeToolDescriptorSchema.parse({ schema_version: McpRuntimeSchemaVersion.RuntimeToolDescriptor, name, description, inputSchema, outputSchema, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true }, riskTier: "low", safety: { readOnly: true, previewOnly: true, fixtureOnly: true, destructive: false, live: false, liveWrite: false, externalSideEffect: false, liveCapabilityStatus: "fixture_only", allowedEffects: ["fixture_memory_graph_read"], hardStopCategories: ["durable_memory_write", "production_memory_mutation", "private_data_ingestion", "secret_storage", "embeddings_provider_call", "vector_database_write"], receiptExpectations: ["memory_graph_receipt_preview", "fixture_only_no_live_write_statement"], evidenceExpectations: ["fixture_memory_graph_summary", "public_safe_output_summary"] }, mcp_compatible: true, app_host_tool: false, repo_status_tool: false, memory_graph_tool: true }); }
export function listMemoryGraphRuntimeTools(): RuntimeToolDescriptor[] { return [ descriptor("memory.graph.preview", "Preview the fixture-only in-memory Memory Graph bundle."), descriptor("memory.node.search.preview", "Search fixture-only Memory Graph nodes by tag, text, confidence, or sensitivity."), descriptor("memory.context.preview", "Produce a fixture-only mission/task Memory Graph context packet."), descriptor("memory.retention.preview", "Produce a fixture-only Memory Graph retention report preview.") ]; }
export function isMemoryGraphRuntimeToolName(name: string): name is MemoryGraphRuntimeToolName { return memoryToolNames.includes(name as MemoryGraphRuntimeToolName); }
export function callMemoryGraphRuntimeTool(name: MemoryGraphRuntimeToolName, input: unknown = {}) { const parsed = input && typeof input === "object" && !Array.isArray(input) ? input as { query?: string; tag?: string; root_node_id?: string; sensitivity?: string; min_confidence?: number } : {}; if (name === "memory.graph.preview") return { graph: memoryGraphFixture, receipt: createMemoryGraphReceiptPreview(memoryGraphFixture), fixture_only: true, live_write: false, durable_storage: false, embeddings: false }; if (name === "memory.node.search.preview") { const byTag = parsed.tag ? searchNodesByTag(memoryGraphFixture, parsed.tag) : []; const byText = parsed.query ? searchNodesByText(memoryGraphFixture, parsed.query) : []; const bySensitivity = parsed.sensitivity ? filterNodesBySensitivity(memoryGraphFixture, parsed.sensitivity as never) : []; const merged = [...new Map([...byTag, ...byText, ...bySensitivity].filter((node) => parsed.min_confidence === undefined || node.confidence >= parsed.min_confidence).map((node) => [node.node_id, node])).values()]; return { nodes: merged, count: merged.length, fixture_only: true, live_write: false }; } if (name === "memory.context.preview") { const packet = produceContextPacket(memoryGraphFixture, parsed.root_node_id ?? "mission:fixture:1"); return { packet, public_safe_summary: producePublicSafeContextSummary(packet), fixture_only: true, live_write: false }; } if (name === "memory.retention.preview") { const report = produceRetentionReport(memoryGraphFixture); return { report, public_safe_summary: producePublicSafeRetentionSummary(report), fixture_only: true, live_write: false, deletion_performed: false }; } throw new Error(`Unknown memory graph runtime tool: ${name}`); }
