import { assertRuntimeToolInventorySafe } from "./app-host-adapter";
import { createDevModeConnectionInfo } from "./dev-mode";
import { MCP_RUNTIME_ID } from "./fixtures";
import { listRuntimeResources, readRuntimeResource } from "./resources";
import { McpRuntimeSchemaVersion } from "./schemas";
import { callRuntimeTool, listRuntimeTools } from "./tool-router";
export interface McpRuntimeServerOptions { runtime_id?: string; local_dev_only?: boolean; }
export function createRuntimeMetadata(options: McpRuntimeServerOptions = {}) { return { schema_version: McpRuntimeSchemaVersion.RuntimeMetadata, runtime_id: options.runtime_id ?? MCP_RUNTIME_ID, build: 10, name: "StealthEye Agent OS MCP Runtime", mode: "local_dev_preview", production_ready: false, public_app_submitted: false, live_write_tools: false, sdk_gap: "Build 10 provides a truthful MCP-style in-process runtime wrapper; full official SDK transport wiring is deferred." }; }
export function getRuntimeHealth(options: McpRuntimeServerOptions = {}) { return { schema_version: McpRuntimeSchemaVersion.RuntimeHealth, status: "ok", runtime_id: options.runtime_id ?? MCP_RUNTIME_ID, build: 10, local_dev_only: options.local_dev_only ?? true, production_ready: false, live_write_capabilities: false, safe_tool_inventory: assertRuntimeToolInventorySafe(), message: "MCP runtime is available for local/dev preview-only calls." }; }
export function getRuntimeCapabilities() { const tools = listRuntimeTools(); return { schema_version: McpRuntimeSchemaVersion.RuntimeCapabilities, tool_families: [...new Set(tools.map((tool) => tool.name.split(".")[0]))].sort(), tool_count: tools.length, resource_count: listRuntimeResources().length, read_only_tools: true, preview_only_or_fixture_only_tools: tools.every((tool) => tool.safety.previewOnly || tool.safety.fixtureOnly), live_capability_status: "disabled", forbidden_capabilities: ["live_repo_mutation", "live_browser_automation", "credentialed_browsing", "money_movement", "production_mutation", "secret_access"] }; }
export function createMcpRuntimeServer(options: McpRuntimeServerOptions = {}) { return { metadata: createRuntimeMetadata(options), health: () => getRuntimeHealth(options), capabilities: () => getRuntimeCapabilities(), devMode: () => createDevModeConnectionInfo(options.runtime_id ?? MCP_RUNTIME_ID), listTools: listRuntimeTools, callTool: (name: string, input?: unknown) => callRuntimeTool(name, input ?? {}), listResources: listRuntimeResources, readResource: readRuntimeResource }; }
