import { assertRuntimeToolInventorySafe } from "./app-host-adapter";
import { createDevModeConnectionInfo } from "./dev-mode";
import { MCP_RUNTIME_ID } from "./fixtures";
import type { RepoStatusRuntimeOptions } from "./repo-status-adapter";
import { listRuntimeResources, readRuntimeResource } from "./resources";
import { McpRuntimeSchemaVersion } from "./schemas";
import { callRuntimeTool, listRuntimeTools } from "./tool-router";
export interface McpRuntimeServerOptions extends RepoStatusRuntimeOptions { runtime_id?: string; local_dev_only?: boolean; }
export function createRuntimeMetadata(options: McpRuntimeServerOptions = {}) { return { schema_version: McpRuntimeSchemaVersion.RuntimeMetadata, runtime_id: options.runtime_id ?? MCP_RUNTIME_ID, build: 13, name: "StealthEye Agent OS MCP Runtime", mode: "local_dev_read_only_repo_status_memory_preview_and_codeops_write_fixture", production_ready: false, public_app_submitted: false, live_read_tools: true, live_write_tools: false, branch_write_fixture_tools: true, sdk_gap: "Build 13 keeps the MCP-style in-process runtime, adds guarded CodeOps branch-write preview/fixture tools, and leaves official SDK transport wiring for Build 14." }; }
export function getRuntimeHealth(options: McpRuntimeServerOptions = {}) { const tools = listRuntimeTools(); return { schema_version: McpRuntimeSchemaVersion.RuntimeHealth, status: "ok", runtime_id: options.runtime_id ?? MCP_RUNTIME_ID, build: 13, local_dev_only: options.local_dev_only ?? true, production_ready: false, live_read_capabilities: true, live_write_capabilities: false, branch_write_fixture_capabilities: true, safe_tool_inventory: assertRuntimeToolInventorySafe(tools), message: "MCP runtime is available for safe App Host previews, Guard/Receipts-wrapped public repo/status reads, fixture-only Memory Graph previews, and guarded CodeOps branch-write previews/fixture execution." }; }
export function getRuntimeCapabilities() { const tools = listRuntimeTools(); return { schema_version: McpRuntimeSchemaVersion.RuntimeCapabilities, tool_families: [...new Set(tools.map((tool) => tool.name.split(".")[0]))].sort(), tool_count: tools.length, resource_count: listRuntimeResources().length, read_only_tools: tools.every((tool) => tool.safety.readOnly), preview_only_or_fixture_only_tools: tools.filter((tool) => !tool.repo_status_tool).every((tool) => tool.safety.previewOnly || tool.safety.fixtureOnly), live_capability_status: "read_only_live_and_fixture_only", live_write_tools: false, branch_write_fixture_tools: tools.filter((tool) => tool.codeops_write_tool).map((tool) => tool.name), repo_status_read_only_tools: tools.filter((tool) => tool.repo_status_tool).map((tool) => tool.name), memory_graph_preview_tools: tools.filter((tool) => tool.memory_graph_tool).map((tool) => tool.name), forbidden_capabilities: ["unrestricted_live_repo_mutation", "protected_branch_write", "direct_main_write", "force_push", "workflow_dispatch", "production_deployment_write", "secret_access", "customer_private_data_access", "ci_test_security_weakening", "live_memory_service", "durable_personal_memory", "vector_database", "embeddings_provider", "live_browser_automation", "credentialed_browsing", "money_movement", "production_mutation", "private_repo_access"] }; }
export function createMcpRuntimeServer(options: McpRuntimeServerOptions = {}) { return { metadata: createRuntimeMetadata(options), health: () => getRuntimeHealth(options), capabilities: () => getRuntimeCapabilities(), devMode: () => createDevModeConnectionInfo(options.runtime_id ?? MCP_RUNTIME_ID), listTools: listRuntimeTools, callTool: (name: string, input?: unknown) => callRuntimeTool(name, input ?? {}, options), listResources: listRuntimeResources, readResource: readRuntimeResource }; }
