import { createHash } from "node:crypto";
import { canonicalize } from "@stealtheye/agent-registry";
import { evaluateGuardDecision, GuardSchemaVersion, type CapabilityToken, type GuardDecision, type RegistryTrustInput, type RequestedAction } from "@stealtheye/guard";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

export const BranchWriteSchemaVersion = { BranchWriteTarget: "codeops-branch-write-target.v1", BranchWriteFileChange: "codeops-branch-write-file-change.v1", BranchWritePlan: "codeops-branch-write-plan.v1", BranchWritePolicy: "codeops-branch-write-policy.v1", BranchWritePolicyDecision: "codeops-branch-write-policy-decision.v1", BranchWriteReceiptPreview: "codeops-branch-write-receipt-preview.v1", BranchWriteResult: "codeops-branch-write-result.v1", WriterCapabilities: "codeops-branch-writer-capabilities.v1" } as const;
export const WriterModeSchema = z.enum(["fixture", "dry_run", "live_config_required"]);
export const BranchWriteChangeTypeSchema = z.enum(["create", "update", "delete_prohibited"]);
export const BranchWriteSensitivitySchema = z.enum(["public", "public_fixture", "generated_public", "unknown"]);
export const BranchWriteDecisionFindingSchema = z.object({ check_id: z.string().min(1), passed: z.boolean(), reason_codes: z.array(z.string().min(1)).default([]), summary: z.string().min(1) });
export const BranchWriteTargetSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWriteTarget), repo_full_name: z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/), default_branch: z.string().min(1).default("main"), protected_branches: z.array(z.string().min(1)).default(["main", "master"]), allowed_branch_prefixes: z.array(z.string().min(1)).default(["agent/"]), allowed_paths: z.array(z.string().min(1)).default([]), denied_paths: z.array(z.string().min(1)).default([]), public_safe: z.literal(true) });
export const BranchWriteFileChangeSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWriteFileChange), path: z.string().min(1), change_type: BranchWriteChangeTypeSchema, content: z.string().max(100000).optional(), patch_summary: z.string().min(1), size_estimate: z.number().int().nonnegative(), public_safe: z.literal(true), sensitivity: BranchWriteSensitivitySchema, generated: z.boolean(), verification_requirement: z.string().min(1) });
export const BranchWritePlanSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWritePlan), mission_id: z.string().min(1), task_id: z.string().min(1), repo_target: BranchWriteTargetSchema, base_branch: z.string().min(1), target_branch: z.string().min(1), branch_prefix: z.string().min(1), file_changes: z.array(BranchWriteFileChangeSchema).min(1), patch_summary: z.string().min(1), verification_commands: z.array(z.string().min(1)).default([]), receipts_expected: z.array(z.string().min(1)).default([]), risk_flags: z.array(z.string().min(1)).default([]), idempotency_key: z.string().min(1), requested_by: z.string().min(1), created_at: z.string().datetime(), mode: WriterModeSchema.default("dry_run"), force_push: z.boolean().default(false), registry_trust_summary: z.object({ trusted: z.boolean(), valid: z.boolean(), trust_status: z.string().min(1), review_status: z.string().min(1), revoked: z.boolean().default(false) }).optional() });
export const BranchWritePolicySchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWritePolicy), allowed_repository: z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/), allowed_branch_prefixes: z.array(z.string().min(1)).default(["agent/"]), protected_branches: z.array(z.string().min(1)).default(["main", "master"]), allowed_paths: z.array(z.string().min(1)).default([]), denied_paths: z.array(z.string().min(1)).default([]), max_file_changes: z.number().int().positive().default(8), max_file_size_bytes: z.number().int().positive().default(20000), max_total_size_bytes: z.number().int().positive().default(60000), require_public_safe: z.literal(true).default(true), require_verification_commands: z.literal(true).default(true), require_receipts: z.literal(true).default(true), allow_generated_or_fixture_only: z.literal(true).default(true), live_mode: WriterModeSchema.default("dry_run") });
export const BranchWritePolicyDecisionSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWritePolicyDecision), decision_id: z.string().min(1), plan_id: z.string().min(1), allowed: z.boolean(), denied: z.boolean(), escalated: z.boolean(), mode: WriterModeSchema, reason_codes: z.array(z.string().min(1)).default([]), warnings: z.array(z.string().min(1)).default([]), findings: z.array(BranchWriteDecisionFindingSchema).default([]), guard_decision_refs: z.array(z.string().min(1)).default([]), created_at: z.string().datetime() });
export const WriterCapabilitiesSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.WriterCapabilities), mode: WriterModeSchema, fixture_only: z.boolean(), dry_run_default: z.boolean(), live_capability_status: z.enum(["disabled", "config_required", "fixture_only"]), allowed_effects: z.array(z.string()), forbidden_effects: z.array(z.string()), max_file_changes: z.number().int().positive(), max_file_size_bytes: z.number().int().positive(), no_force_push: z.literal(true), no_protected_branch: z.literal(true), no_workflow_mutation: z.literal(true), no_secrets: z.literal(true), no_production_mutation: z.literal(true) });
export const BranchWriteReceiptPreviewSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWriteReceiptPreview), receipt_preview_id: z.string().min(1), mission_id: z.string().min(1), task_id: z.string().min(1), mode: WriterModeSchema, events: z.array(z.unknown()).default([]), event_summaries: z.array(z.string()).default([]), public_safe: z.literal(true), durable_ledger: z.literal(false), created_at: z.string().datetime() });
export const BranchWriteResultSchema = z.object({ schema_version: z.literal(BranchWriteSchemaVersion.BranchWriteResult), result_id: z.string().min(1), mode: WriterModeSchema, status: z.enum(["previewed", "fixture_executed", "denied", "live_config_required"]), plan: BranchWritePlanSchema, policy_decision: BranchWritePolicyDecisionSchema, guard_decision_refs: z.array(z.string()).default([]), receipt_preview: BranchWriteReceiptPreviewSchema, changed_paths: z.array(z.string()).default([]), verification_commands: z.array(z.string()).default([]), summary: z.string().min(1), created_at: z.string().datetime() });
export type WriterMode = z.infer<typeof WriterModeSchema>; export type BranchWritePlan = z.infer<typeof BranchWritePlanSchema>; export type BranchWritePolicy = z.infer<typeof BranchWritePolicySchema>; export type BranchWriteDecisionFinding = z.infer<typeof BranchWriteDecisionFindingSchema>; export type BranchWritePolicyDecision = z.infer<typeof BranchWritePolicyDecisionSchema>; export type BranchWriteReceiptPreview = z.infer<typeof BranchWriteReceiptPreviewSchema>; export type BranchWriteResult = z.infer<typeof BranchWriteResultSchema>; export type WriterCapabilities = z.infer<typeof WriterCapabilitiesSchema>;
export const BranchWriteJsonSchemas = { target: zodToJsonSchema(BranchWriteTargetSchema, "BranchWriteTarget"), fileChange: zodToJsonSchema(BranchWriteFileChangeSchema, "BranchWriteFileChange"), plan: zodToJsonSchema(BranchWritePlanSchema, "BranchWritePlan"), policy: zodToJsonSchema(BranchWritePolicySchema, "BranchWritePolicy"), policyDecision: zodToJsonSchema(BranchWritePolicyDecisionSchema, "BranchWritePolicyDecision") };
function stablePayload(plan: BranchWritePlan): unknown { return { mission_id: plan.mission_id, task_id: plan.task_id, repo: plan.repo_target.repo_full_name, base_branch: plan.base_branch, target_branch: plan.target_branch, files: plan.file_changes.map(c => ({ path: c.path, change_type: c.change_type, patch_summary: c.patch_summary, generated: c.generated })).sort((a,b)=>a.path.localeCompare(b.path)), verification_commands: [...plan.verification_commands].sort(), receipts_expected: [...plan.receipts_expected].sort(), risk_flags: [...plan.risk_flags].sort(), requested_by: plan.requested_by }; }
export function createBranchWriteIdempotencyKey(plan: BranchWritePlan): string { return `branch-write:${createHash("sha256").update(canonicalize(stablePayload(plan)), "utf8").digest("hex").slice(0,24)}`; }
function action(plan: BranchWritePlan, stage: string, effect: RequestedAction["effect"], path?: string): RequestedAction { return { schema_version: GuardSchemaVersion.RequestedAction, action_id: `branch-write-action:${plan.mission_id}:${plan.task_id}:${stage}`, mission_id: plan.mission_id, actor_id: plan.requested_by, subject_type: "agent", effect, target: { repo: plan.repo_target.repo_full_name, branch: plan.target_branch, ...(path ? { path } : {}), system: "github", environment: "development", account: plan.repo_target.repo_full_name.split("/")[0] ?? "unknown" }, agent_id: plan.requested_by, manifest_id: "tool-manifest:codeops-branch-write-fixture", risk_indicators: [...plan.risk_flags, ...plan.file_changes.flatMap(c => [c.patch_summary, c.verification_requirement])], side_effects: effect === "read_repo" ? [] : ["branch_write_fixture_or_preview_only"], requested_at: plan.created_at, idempotency_key: `${plan.idempotency_key}:${stage}`, metadata: { build: 13, stage, mode: plan.mode, fixture_or_preview_only: true }, evidence_refs: [`evidence:${plan.mission_id}:${plan.task_id}:${stage}`] }; }
const ciWeakening = /skip\s+tests?|disable\s+(ci|test|typecheck|lint|security)|remove\s+(ci|test|typecheck|lint|security)|weaken\s+(ci|test|typecheck|lint|security)|continue-on-error\s*:\s*true|--passWithNoTests|test\.skip\s*\(|describe\.skip\s*\(|it\.skip\s*\(|\.only\s*\(/i;
export function requestedActionsForBranchWritePlan(plan: BranchWritePlan): RequestedAction[] { const txt = [plan.patch_summary, ...plan.risk_flags, ...plan.file_changes.flatMap(c=>[c.path,c.patch_summary,c.content??""])].join("\n"); const actions = [action(plan,"repo-branch-read","read_repo"), action(plan,"branch-create","write_branch_files"), ...plan.file_changes.filter(c=>c.change_type!=="delete_prohibited").map(c=>action(plan,`file-write:${c.path}`,"write_branch_files",c.path)), action(plan,"commit","commit_branch"), action(plan,"pr-open-preview","open_pr"), action(plan,"receipt-write","write_receipt")]; if (plan.target_branch === plan.base_branch || plan.target_branch === plan.repo_target.default_branch || plan.repo_target.protected_branches.includes(plan.target_branch)) actions.push(action(plan,"protected-branch","protected_branch_mutation")); if (plan.force_push || /force\s*push|history\s*rewrite/i.test(txt)) actions.push(action(plan,"force-push","force_push")); if (ciWeakening.test(txt)) actions.push(action(plan,"weaken-ci","weaken_ci")); if (plan.file_changes.some(c=>c.change_type==="delete_prohibited")) actions.push(action(plan,"delete-prohibited","destructive_delete")); if (plan.file_changes.some(c=>/(^|\/)(\.env|secrets?|credentials?|tokens?|private-key|oauth-client|service-account)(\.|\/|$)/i.test(c.path))) actions.push(action(plan,"credential-like-path","raw_secret_access")); if (plan.file_changes.some(c=>/(^|\/)(prod|production|deploy\/production|infra\/production|terraform\/production)(\/|\.|$)/i.test(c.path))) actions.push(action(plan,"production-path","production_deploy")); return actions; }
export function guardDecisionsForBranchWritePlan(input: { plan: BranchWritePlan; capability_tokens: CapabilityToken[]; registry_trust_summary?: RegistryTrustInput | undefined }): GuardDecision[] { return requestedActionsForBranchWritePlan(input.plan).map(a => evaluateGuardDecision(a, input.capability_tokens, { now: new Date(input.plan.created_at), ...(input.registry_trust_summary ? { registryTrust: input.registry_trust_summary } : {}), decisionId: `guard-decision:${a.action_id}` })); }
